import ContentImage from '../../../components/content-image';
import Link from 'next/link';
import {requireStaff} from '../../../lib/supabase';
import {kinds} from '../../../lib/content';
import {postCoverPath} from '../../../lib/post-cover';
import Icon from '../../../components/admin-icon';
const statusNames:Record<string,string>={draft:'খসড়া',review:'পর্যালোচনা',published:'প্রকাশিত',archived:'আর্কাইভ'};
export default async function Content({searchParams}:{searchParams:Promise<{page?:string;q?:string;status?:string;kind?:string;photo?:string}>}){
 const {db}=await requireStaff(),params=await searchParams;
 const page=Math.max(1,Math.floor(Number(params.page)||1)),term=(params.q??'').trim().slice(0,80),status=Object.hasOwn(statusNames,params.status??'')?params.status??'':'',kind=Object.hasOwn(kinds,params.kind??'')?params.kind??'':'';
 const missingPhoto=params.photo==='missing';
 let query=db.from('cumilla_posts').select('id,title,kind,status,updated_at,cover_url,media_paths,cover_selection',{count:'exact'});
 if(term)query=query.ilike('title',`%${term}%`);if(status)query=query.eq('status',status);if(kind)query=query.eq('kind',kind);
 if(missingPhoto)query=query.or('cover_selection.eq.none,and(cover_selection.is.null,cover_url.is.null,media_paths.eq.{})');
 const {data,error,count}=await query.order('updated_at',{ascending:false}).range((page-1)*20,page*20-1);if(error)throw error;
 const rows=await Promise.all((data??[]).map(async p=>{const path=postCoverPath(p);return {...p,image:path?(path.startsWith('https://')?'/media-proxy?url='+encodeURIComponent(path):(await db.storage.from('cumilla-media').createSignedUrl(path,3600)).data?.signedUrl):null};}));
 const href=(next:number,nextStatus=status)=>{const q=new URLSearchParams();if(term)q.set('q',term);if(nextStatus)q.set('status',nextStatus);if(kind)q.set('kind',kind);if(missingPhoto)q.set('photo','missing');if(next>1)q.set('page',String(next));return '/admin/content'+(q.size?'?'+q:'');};
 return <section><div className="admin-page-header"><div><p className="eyebrow">কনটেন্ট লাইব্রেরি</p><h1>{kind?kinds[kind]:'সব প্রকাশনা'}</h1><p>লেখা খুঁজুন, ছবি মিলিয়ে দেখুন, সরাসরি সম্পাদনা করুন।</p></div><div className="admin-page-actions"><Link className="admin-btn primary" href={'/admin/content/new'+(kind?'?kind='+kind:'')}><Icon name="plus" size={18}/>নতুন প্রকাশনা</Link></div></div><nav className="studio-tabs" aria-label="প্রকাশনার অবস্থা">{[['','সব কনটেন্ট'],...Object.entries(statusNames)].map(([s,label])=><Link key={s} href={href(1,s)} aria-current={status===s?'page':undefined}>{label}</Link>)}</nav><div className="admin-toolbar"><form className="admin-filters" method="get"><input name="q" defaultValue={term} placeholder="শিরোনাম দিয়ে খুঁজুন…" aria-label="প্রকাশনা খুঁজুন"/>{status&&<input type="hidden" name="status" value={status}/>}<select name="kind" defaultValue={kind} aria-label="বিভাগ"><option value="">সব বিভাগ</option>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select name="photo" defaultValue={missingPhoto?'missing':''} aria-label="ছবির অবস্থা"><option value="">সব ছবি</option><option value="missing">ছবি বাকি</option></select><button type="submit">খুঁজুন</button>{(term||kind||missingPhoto)&&<Link className="admin-filter-reset" href="/admin/content">রিসেট</Link>}</form></div><p className="studio-result-count">{(count??0).toLocaleString('bn-BD')}টি প্রকাশনা</p><div className="admin-table">{rows.map(p=><Link className="admin-row" key={p.id} href={'/admin/content/'+p.id}>{p.image?<ContentImage key={p.image} className="studio-thumb" src={p.image} alt="" compact/>:<span className="studio-thumb"><Icon name="image"/></span>}<div className="admin-row-title"><strong>{p.title}</strong>{!p.image&&<span className="studio-missing-photo">ছবি বাকি</span>}<small>সর্বশেষ সম্পাদনা · {new Date(p.updated_at).toLocaleDateString('bn-BD',{timeZone:'Asia/Dhaka'})}</small></div><span className="admin-row-kind">{kinds[p.kind]??p.kind}</span><span className={'admin-status '+p.status}>{statusNames[p.status]}</span><span className="admin-row-arrow"><Icon name="arrow" size={18}/></span></Link>)}{!rows.length&&<div className="admin-empty"><Icon name="search" size={30}/><p>কোনো প্রকাশনা পাওয়া যায়নি।</p><Link className="admin-btn" href="/admin/content">সব প্রকাশনা দেখুন</Link></div>}</div><nav className="admin-pagination" aria-label="পৃষ্ঠা পরিবর্তন"><span>{page>1&&<Link href={href(page-1)}>← আগের</Link>}</span><span>পৃষ্ঠা {page.toLocaleString('bn-BD')} / {Math.max(1,Math.ceil((count??0)/20)).toLocaleString('bn-BD')}</span><span>{page*20<(count??0)&&<Link href={href(page+1)}>পরের →</Link>}</span></nav></section>;
}
